// OUT-005 exception: test skip-signal writes to stderr are legitimate test-harness
// communication (not library output). The Output struct cannot be used here.
#![allow(clippy::print_stderr)]
//! Drift guard: vendored violation test files in `.ckeletin/tests/violations/`
//! must be byte-identical to their active project copies under the declared
//! domain/infrastructure crate test directories.
//!
//! **Why:** the vendored copies are the canonical versions that propagate to
//! consumer repos via `just ckeletin-update`. The project copies are what the
//! trybuild tests actually run. If they diverge, a consumer gets stale violation
//! tests and the enforcement claim is backed by different code than what runs.
//!
//! **Behavior matrix (mirrors arch_allowlist.rs):**
//!   a. Config present + violation_tests.enabled → compare declared dirs strictly
//!   b. Config absent + scaffold layout present → compare default dirs
//!   c. Config absent + scaffold layout absent → SKIP LOUDLY
//!   d. violation_tests.enabled = false → SKIP LOUDLY (consumer opted out)
//!
//! **Configuration:** consumers control this via `ckeletin-project.toml`
//! (`[violation_tests] enabled = false` to opt out; custom `domain_dirs` /
//! `infra_dirs` for non-scaffold layouts). Do NOT edit this file.

use std::collections::HashMap;

use ckeletin::project_config;

/// Resolve the workspace root from CARGO_MANIFEST_DIR (.ckeletin/crate).
fn workspace_root() -> std::path::PathBuf {
    let manifest_dir = env!("CARGO_MANIFEST_DIR"); // .ckeletin/crate
    std::path::Path::new(manifest_dir)
        .parent()
        .and_then(|p| p.parent())
        .unwrap()
        .to_path_buf()
}

/// Build the list of (vendored_path, project_path) pairs to compare.
///
/// Vendored files live under `.ckeletin/tests/violations/`.
/// Project copies live under `<layer>/tests/violations/`.
///
/// For the scaffold layout the domain/infra dirs come from project_config
/// defaults.  For custom layouts they come from the declared layer paths plus
/// any extra dirs in `[violation_tests]`.
fn violation_file_pairs(
    root: &std::path::Path,
    config: &project_config::ProjectConfig,
) -> Vec<(std::path::PathBuf, std::path::PathBuf)> {
    let vendored_dir = root.join(".ckeletin/tests/violations");
    let mut pairs = Vec::new();

    // Collect all violation test directories to check.
    let mut dirs: Vec<std::path::PathBuf> = Vec::new();

    // Domain layer dirs.
    for domain_dir in &config.layers.domain {
        dirs.push(root.join(domain_dir).join("tests/violations"));
    }
    for extra in &config.violation_tests.domain_dirs {
        dirs.push(root.join(extra));
    }

    // Infrastructure layer dirs.
    for infra_dir in &config.layers.infrastructure {
        dirs.push(root.join(infra_dir).join("tests/violations"));
    }
    for extra in &config.violation_tests.infra_dirs {
        dirs.push(root.join(extra));
    }

    // For each vendored file, check if a matching file exists in any project dir.
    if let Ok(entries) = std::fs::read_dir(&vendored_dir) {
        for entry in entries.flatten() {
            let vendored_path = entry.path();
            if vendored_path.extension().is_none_or(|e| e != "rs") {
                continue;
            }
            let file_name = entry.file_name();
            // Find the project copy in any of the declared dirs.
            for project_dir in &dirs {
                let project_path = project_dir.join(&file_name);
                if project_path.exists() {
                    pairs.push((vendored_path.clone(), project_path));
                    break;
                }
            }
        }
    }

    pairs
}

#[test]
fn vendored_violation_tests_are_byte_identical_to_project_copies() {
    let root = workspace_root();

    let outcome = project_config::load(&root)
        .unwrap_or_else(|e| panic!("ckeletin-project.toml parse error: {e}"));

    if outcome.should_skip() {
        eprintln!(
            "SKIP vendored_violation_tests_are_byte_identical_to_project_copies: \
             no ckeletin-project.toml and scaffold layout absent.\n\
             Declare your layer crates in ckeletin-project.toml at the workspace \
             root to enable this drift guard."
        );
        return;
    }

    let config = outcome.config();

    if !config.violation_tests.enabled {
        eprintln!(
            "SKIP vendored_violation_tests_are_byte_identical_to_project_copies: \
             violation_tests.enabled = false in ckeletin-project.toml."
        );
        return;
    }

    let pairs = violation_file_pairs(&root, config);
    // Zero pairs is legal (a consumer layout that carries no project copies
    // of the violation tests has nothing to compare) — but say so loudly
    // rather than green-lighting in silence, consistent with the skip paths
    // above.
    if pairs.is_empty() {
        eprintln!(
            "SKIP vendored_violation_tests_are_byte_identical_to_project_copies: \
             no vendored/project violation-test pairs found for the declared \
             layers — nothing to compare."
        );
        return;
    }
    let mut failures: HashMap<String, String> = HashMap::new();

    for (vendored_path, active_path) in &pairs {
        let vendored = match std::fs::read(vendored_path) {
            Ok(b) => b,
            Err(e) => {
                failures.insert(
                    vendored_path.display().to_string(),
                    format!(
                        "cannot read vendored file {}: {}",
                        vendored_path.display(),
                        e
                    ),
                );
                continue;
            }
        };

        let active = match std::fs::read(active_path) {
            Ok(b) => b,
            Err(e) => {
                failures.insert(
                    active_path.display().to_string(),
                    format!("cannot read active file {}: {}", active_path.display(), e),
                );
                continue;
            }
        };

        if vendored != active {
            failures.insert(
                vendored_path.display().to_string(),
                format!(
                    "vendored {} differs from active {}; copy the canonical version to reconcile:\n  cp {} {}",
                    vendored_path.display(),
                    active_path.display(),
                    vendored_path.display(),
                    active_path.display(),
                ),
            );
        }
    }

    assert!(
        failures.is_empty(),
        "Vendored violation tests diverged from project copies ({} pair(s)):\n{}",
        failures.len(),
        failures.values().cloned().collect::<Vec<_>>().join("\n")
    );
}
